DRIVERS_OBJS += $(LINKDIR)vga.o

driver_display:
	@echo Target: drivers.display
	@echo Drivers.display: [CC] vga.o
	@gcc $(GCCOPTS) -o $(LINKDIR)vga.o drivers/display/vga.c
	@echo Drivers.display compilling done!