name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: ilammy/setup-nasm@v1
    - name: Compile
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Kernel
        papth: out.kern

